<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="GOROroba" nsURI="http://nemo.inf.ufes.br/GOROOld" nsPrefix="gororoba">
  <eClassifiers xsi:type="ecore:EClass" name="Container">
    <eStructuralFeatures xsi:type="ecore:EReference" name="requirements" upperBound="-1"
        eType="#//Requirement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assumptions" upperBound="-1"
        eType="#//AssumptionArtifact" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stakeholders" upperBound="-1"
        eType="#//Stakeholder" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tasks" upperBound="-1"
        eType="#//Task" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntentionalMoment" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inheresin" lowerBound="1"
        upperBound="-1" eType="#//Agent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MentalMoment" abstract="true" eSuperTypes="#//IntentionalMoment"/>
  <eClassifiers xsi:type="ecore:EClass" name="Belief" abstract="true" eSuperTypes="#//MentalMoment"/>
  <eClassifiers xsi:type="ecore:EClass" name="Intention" abstract="true" eSuperTypes="#//MentalMoment"/>
  <eClassifiers xsi:type="ecore:EClass" name="Desire" abstract="true" eSuperTypes="#//MentalMoment"/>
  <eClassifiers xsi:type="ecore:EClass" name="Agent" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Stakeholder" abstract="true" eSuperTypes="#//Agent"/>
  <eClassifiers xsi:type="ecore:EClass" name="StakeholderBelief" eSuperTypes="#//Belief"/>
  <eClassifiers xsi:type="ecore:EClass" name="RequirementsStakeholder" eSuperTypes="#//Stakeholder">
    <eStructuralFeatures xsi:type="ecore:EReference" name="interestedIn" lowerBound="1"
        upperBound="-1" eType="#//RequirementArtifact"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Proposition"/>
  <eClassifiers xsi:type="ecore:EClass" name="Goal" eSuperTypes="#//Proposition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="propositionalContentOfDesire"
        lowerBound="1" upperBound="-1" eType="#//Desire"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="propositionalContentOfBelief"
        lowerBound="1" upperBound="-1" eType="#//Intention"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RequirementArtifact">
    <eStructuralFeatures xsi:type="ecore:EReference" name="describes" lowerBound="1"
        eType="#//Requirement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StakeholderIntention" eSuperTypes="#//Intention"/>
  <eClassifiers xsi:type="ecore:EClass" name="Requirement" eSuperTypes="#//Goal">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elicitedFrom" lowerBound="1"
        upperBound="-1" eType="#//RequirementsStakeholder"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refinements" upperBound="-1"
        eType="#//Requirement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="refinementType" eType="#//RefinementType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operationalizations" upperBound="-1"
        eType="#//Task" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StakeholderDesire" eSuperTypes="#//Desire"/>
  <eClassifiers xsi:type="ecore:EClass" name="NonFunctionalRequirement" eSuperTypes="#//Requirement"/>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionalRequirement" eSuperTypes="#//Requirement"/>
  <eClassifiers xsi:type="ecore:EClass" name="GoalBasedRequirement" eSuperTypes="#//Requirement"/>
  <eClassifiers xsi:type="ecore:EClass" name="GoalBasedRequirementArtifact" eSuperTypes="#//RequirementArtifact"/>
  <eClassifiers xsi:type="ecore:EClass" name="GoalBasedRequirementSpecification" eSuperTypes="#//RequirementDocument">
    <eStructuralFeatures xsi:type="ecore:EReference" name="gbra" upperBound="-1" eType="#//GoalBasedRequirementArtifact"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assumptions" upperBound="-1"
        eType="#//AssumptionArtifact" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RequirementDocument">
    <eStructuralFeatures xsi:type="ecore:EReference" name="documents" lowerBound="1"
        upperBound="-1" eType="#//RequirementArtifact" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RequirementsEngineer" eSuperTypes="#//Stakeholder">
    <eStructuralFeatures xsi:type="ecore:EReference" name="responsibleFor" upperBound="-1"
        eType="#//RequirementDocument"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Assumption" eSuperTypes="#//Proposition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="propositionalContentOf"
        lowerBound="1" upperBound="-1" eType="#//StakeholderBelief"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elicitedFrom" lowerBound="1"
        upperBound="-1" eType="#//RequirementsStakeholder"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AssumptionArtifact">
    <eStructuralFeatures xsi:type="ecore:EReference" name="describes" lowerBound="1"
        eType="#//Assumption"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Hardgoal" eSuperTypes="#//GoalBasedRequirement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Softgoal" eSuperTypes="#//GoalBasedRequirement"/>
  <eClassifiers xsi:type="ecore:EClass" name="NonFunctionalRequirementArtifact" eSuperTypes="#//RequirementArtifact"/>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionalRequirementArtifact" eSuperTypes="#//RequirementArtifact"/>
  <eClassifiers xsi:type="ecore:EClass" name="NonFunctionalGoalBasedRequirementArtifact"
      eSuperTypes="#//NonFunctionalRequirement"/>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionalHardgoalRequirementArtifact"
      eSuperTypes="#//Hardgoal #//FunctionalRequirement"/>
  <eClassifiers xsi:type="ecore:EClass" name="NonFunctionalSoftgoalRequirementArtifact"
      eSuperTypes="#//NonFunctionalRequirementArtifact #//Softgoal"/>
  <eClassifiers xsi:type="ecore:EClass" name="ActionUniversalPlan" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Task" eSuperTypes="#//ActionUniversalPlan">
    <eStructuralFeatures xsi:type="ecore:EReference" name="intendsToOperationalize"
        lowerBound="1" upperBound="-1" eType="#//GoalBasedRequirementArtifact"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComplexTask" eSuperTypes="#//Task">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tasks" lowerBound="2" upperBound="-1"
        eType="#//Task" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="refinementType" eType="#//RefinementType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AtomicTask" eSuperTypes="#//Task"/>
  <eClassifiers xsi:type="ecore:EClass" name="AtomicGoalBasedRequirementArtiact" eSuperTypes="#//GoalBasedRequirementArtifact"/>
  <eClassifiers xsi:type="ecore:EClass" name="ComplexGoalBasedRequirementArtifact"
      eSuperTypes="#//GoalBasedRequirementArtifact">
    <eStructuralFeatures xsi:type="ecore:EReference" name="refinements" lowerBound="1"
        upperBound="-1" eType="#//GoalBasedRequirementArtifact" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AndComplexGoalBasedRequirementArtifact"
      eSuperTypes="#//ComplexGoalBasedRequirementArtifact"/>
  <eClassifiers xsi:type="ecore:EClass" name="OrComplexGoalBasedRequirementArtifact"
      eSuperTypes="#//ComplexGoalBasedRequirementArtifact"/>
  <eClassifiers xsi:type="ecore:EEnum" name="RefinementType">
    <eLiterals name="AND" value="1"/>
    <eLiterals name="OR"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NonFunctionalHardgoalRequirementArtifact"
      eSuperTypes="#//Hardgoal #//NonFunctionalRequirementArtifact"/>
  <eClassifiers xsi:type="ecore:EClass" name="Situation"/>
  <eClassifiers xsi:type="ecore:EClass" name="ThreateningSituation" eSuperTypes="#//Situation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="satisfies" upperBound="-1"
        eType="#//ThreateningProposition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ThreateningProposition" eSuperTypes="#//Proposition"/>
  <eClassifiers xsi:type="ecore:EClass" name="Obstacle"/>
  <eClassifiers xsi:type="ecore:EClass" name="MitigationTask" eSuperTypes="#//Task">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mitigates" lowerBound="1"
        upperBound="-1" eType="#//Obstacle"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContingencyTask" eSuperTypes="#//Task">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contingencies" lowerBound="1"
        upperBound="-1" eType="#//Obstacle"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComplexObstacle" eSuperTypes="#//Obstacle">
    <eStructuralFeatures xsi:type="ecore:EReference" name="obstacles" lowerBound="2"
        upperBound="-1" eType="#//Obstacle" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AtomicObstacle" eSuperTypes="#//Obstacle"/>
  <eClassifiers xsi:type="ecore:EClass" name="AndComplexObstacle" eSuperTypes="#//ComplexObstacle"/>
  <eClassifiers xsi:type="ecore:EClass" name="OrComplexObstacle" eSuperTypes="#//ComplexObstacle"/>
  <eClassifiers xsi:type="ecore:EClass" name="Contribution">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//ContributionType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="intensity" eType="#//ContributionType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="goalMediation" lowerBound="1"
        eType="#//GoalBasedRequirementArtifact"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nfrMediation" eType="#//NonFunctionalGoalBasedRequirementArtifact"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ContributionType">
    <eLiterals name="positive" value="1"/>
    <eLiterals name="negative"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ContributionIntensity">
    <eLiterals name="partial" literal="partial"/>
    <eLiterals name="total" value="1" literal="total"/>
  </eClassifiers>
</ecore:EPackage>
