<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="goro" nsURI="http://nemo.inf.ufes.br/GORO" nsPrefix="goro">
  <eClassifiers xsi:type="ecore:EClass" name="GOROContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="GOREElements" upperBound="-1"
        eType="#//GOREElementArtifact" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stakeholders" upperBound="-1"
        eType="#//Stakeholder" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Contributions" upperBound="-1"
        eType="#//Contribution" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GOREElementArtifact" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Stakeholder">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interests" upperBound="-1"
        eType="#//GOREElementArtifact"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GoalBasedRequirement" eSuperTypes="#//GOREElementArtifact">
    <eStructuralFeatures xsi:type="ecore:EReference" name="conflictsWith" upperBound="-1"
        eType="#//GoalBasedRequirement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refinements" upperBound="-1"
        eType="#//GoalBasedRequirement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="refinementType" eType="#//refinementType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operationalizations" upperBound="-1"
        eType="#//Task" containment="true" eOpposite="#//Task/operationalizationedGoal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionalHardgoal" eSuperTypes="#//GoalBasedRequirement"/>
  <eClassifiers xsi:type="ecore:EClass" name="NonFunctionalHardgoal" eSuperTypes="#//GoalBasedRequirement"/>
  <eClassifiers xsi:type="ecore:EClass" name="NonFunctionalSoftgoal" eSuperTypes="#//GoalBasedRequirement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Obstacle" eSuperTypes="#//GOREElementArtifact">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" upperBound="-1"
        eType="#//GoalBasedRequirement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refinements" upperBound="-1"
        eType="#//Obstacle" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="refinementType" eType="#//refinementType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Contribution">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//GOREElementArtifact"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//NonFunctionalSoftgoal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//contributionType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="intensity" eType="#//contributionIntensity"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Task" eSuperTypes="#//GOREElementArtifact">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operationalizationedGoal"
        eType="#//GoalBasedRequirement" eOpposite="#//GoalBasedRequirement/operationalizations"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
        eType="#//Task" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="refinementType" eType="#//refinementType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="refinementType">
    <eLiterals name="OR" value="1"/>
    <eLiterals name="AND" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="contributionType">
    <eLiterals name="positive" value="1"/>
    <eLiterals name="negative" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="contributionIntensity">
    <eLiterals name="total" value="1"/>
    <eLiterals name="partial" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Assumption" eSuperTypes="#//GOREElementArtifact">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//GoalBasedRequirement"/>
  </eClassifiers>
</ecore:EPackage>
