<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="iStar" nsURI="https://nemo.inf.ufes.br/iStar" nsPrefix="istar">
  <eClassifiers xsi:type="ecore:EClass" name="Intentional Element" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Actor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="intentionalelements" upperBound="-1"
        eType="#//Intentional%20Element" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="is-a" upperBound="-1" eType="#//Actor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="participates-in" upperBound="-1"
        eType="#//Actor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contribution" upperBound="-1"
        eType="#//Quality"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="contribution type" eType="#//Contribution%20Type"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Agent" eSuperTypes="#//Actor"/>
  <eClassifiers xsi:type="ecore:EClass" name="Role" eSuperTypes="#//Actor"/>
  <eClassifiers xsi:type="ecore:EClass" name="Quality" eSuperTypes="#//Intentional%20Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="qualify-resource" upperBound="-1"
        eType="#//Resource"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="qualify-goal-task" upperBound="-1"
        eType="#//GoalTask%20Element"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Resource" eSuperTypes="#//Intentional%20Element"/>
  <eClassifiers xsi:type="ecore:EClass" name="GoalTask Element" abstract="true" eSuperTypes="#//Intentional%20Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="refinements" upperBound="-1"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="refinement-type" eType="#//Refinement%20Type"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Goal" eSuperTypes="#//GoalTask%20Element"/>
  <eClassifiers xsi:type="ecore:EClass" name="Task" eSuperTypes="#//GoalTask%20Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="needs" upperBound="-1"
        eType="#//Resource"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Refinement" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Dependency">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependee" lowerBound="1"
        eType="#//Actor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="depender" lowerBound="1"
        eType="#//Actor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependum" lowerBound="1"
        eType="#//Intentional%20Element"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependerElm" lowerBound="1"
        eType="#//Intentional%20Element"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependeeElm" lowerBound="1"
        eType="#//Intentional%20Element"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Contribution Type">
    <eLiterals name="make" literal="make"/>
    <eLiterals name="help" value="2" literal="help"/>
    <eLiterals name="hurt" value="2" literal="hurt"/>
    <eLiterals name="break" value="3" literal="break"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Refinement Type">
    <eLiterals name="AND"/>
    <eLiterals name="OR" value="1"/>
  </eClassifiers>
</ecore:EPackage>
